### ISSUE TITLE
Hotspot in Nexus 4

### ISSUE THREAD

**Issue by Daniel20000522** [ubports/system-settings#1]
Hi,
Nexus 4 does not have Hotspot. Why?

**Comment by cibersheep** [comment]
Is this still ocurring?

**Comment by Daniel20000522** [comment]
Yes. I am currently using the dev channel. Version 328.
By typing "Hotspot" I see something like that.
![screenshot20190624_223314468](https://user-images.githubusercontent.com/30577245/60050142-377fd800-96d0-11e9-978c-2e15d8cf1417.png)

**Comment by cibersheep** [comment]
I see

**Comment by dobey** [comment]
Yes, it is explicitly hidden on both mako and flo devices. It is disabled on mako (Nexus 4) due to https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1434591

**Comment by UniversalSuperBox** [comment]
Closing due to reason in previous comment
