### ISSUE TITLE
add values higher than 10 minutes to "Lock when idle" in SystemSettings

### ISSUE THREAD

**Issue by balcy** [ubports/system-settings#10]
as a feature request:
sometimes I need the phone to be unlocked for slightly more than 10 minutes (e.g. 15 or 20 minutes)
In this case I usally set "Lock when idle" to "never", and switch it back to 10 minutes later (which is the highest available value right now)

If I forget switching it back, the screen could remain on forever (and discharge the phone quickly)

So adding more options to this list (or a custom value) would be helpful.

**Comment by UniversalSuperBox** [comment]
https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/10
