### ISSUE TITLE
Improve `Reinstall all apps` UX

### ISSUE THREAD

**Issue by myii** [ubports/system-settings#100]
Asked this in [UX Telegram group](https://t.me/UBports_UX) before opening this issue:

> Relatively new UBports user, browsing through the settings to gain familiarity.  Come across `Settings > Updates > Update settings > Reinstall all apps`.  Now this has the `>` on the right side, indicating a further menu/page.  Of course, there is another page but the reinstallation commences immediately, without any chance to confirm that action.  No obvious way to back out once this starts, either.  From a UX perspective, I would be expecting to browse the menu/page and then hitting a button to start this process.

**Comment by lionelb123** [comment]
I just went through this process with both FP2 and BQ FHD, on rc 2018-48
There is an update all button and individual apps have a pause button once that is activated. An oddity was reverse order loading. ZtoA on the FHD but AtoZ on the FP2
After reinstalling 'all' apps on the FP2 and then heading to Check for Updates in Settings I found six apps there listed as having an update available
When I updated those, they loaded in reverse order [is it random?]

**Comment by pbonnell** [comment]
2018-48, Nexus 5

- [x] added menu page shows
- [x]  Reinstall all apps buttons shows
- [x] button click runs 'Checking for updates....'
- [x] page lists individual apps for update
- [x] individual apps update as expected
- [x] Reinstall all apps button updates all remaining apps that need it

On subsequent reload of this page and Reinstall all apps button: 
- 'Checking for updates...' routine crashed Settings ( to Apps scope ). On return 15 updates were available in Settings main and Reinstall all apps
- [x] update all button worked as expected here

**Comment by myii** [comment]
@lionelb123 @pbonnell Thank you both for your time spent testing and your comments.

For clarity, the only change that was proposed by this issue (and implemented in #102) was to add the `Reinstall all apps` button to the page, to prevent the whole process starting immediately when first entering the page.  The actual main functionality of installing apps wasn't touched.  It may be worth considering opening new issues for the problems that you encountered.

**Comment by UniversalSuperBox** [comment]
I was able to get Settings to crash on this page on my Fairphone 2 once, but I haven't been able to reproduce it. Subsequent attempts have been successful.

**Comment by tjrhodes** [comment]
Device: FP2
System Build: 2018-W48

Issue solved, no side affects.

I get a screen with an explanation that this is typically needed after a major update, a big fat green button to start the process and a status message saying "Software is up to date" in my case.

**Comment by andrisk-dev** [comment]
Device: Nexus 5
Build: 2018-W48

Issue solved - new screen with explanation and button + "Software is up to date" appears
