### ISSUE TITLE
System update notification icons are reversed

### ISSUE THREAD

**Issue by dobey** [ubports/system-settings#101]
In the notification for the system updates, the symbolic icon is placed on the left side, which has an inset UbuntuShape, and is not colorized, while the app icon is unshaped and on the right side. This is a bit ugly, as the app icon is meant to be cropped to shape, while the symbolic icon is meant to be colorized.

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/101
