### ISSUE TITLE
Connecting to a wifi network

### ISSUE THREAD

**Issue by mihaelmilea** [ubports/system-settings#11]
In the wifi settings, when selecting a wifi network it immediately says "connected" while the phone is in fact not connected to the network yet and it doesn't have an IP assigned yet. It should say "connecting" instead and then say "connected" only when it has an IP.

Another thing related: when it says "connected" while it is still trying to get an IP, I can see that it doesn't have an IP yet by clicking on the network. There, a new screen opens where there is no IP displayed. Now: this screen though does not auto-refresh itself and the IP does not appear here when it finally gets one. I have to exit to the previous screen and click on the network again in order to see the IP.

**Comment by UniversalSuperBox** [comment]
https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/11
