### ISSUE TITLE
Reinstall all apps does not get translated

### ISSUE THREAD

**Issue by Danfro** [ubports/system-settings#113]
The text "Reinstall all apps" does not get translated (System settings -> updates -> update settings).
I could not find it on weblate available for translation (i.e. search for reinstall).
BQ E5 with 16.04 rc 2018-W48

![screenshot20181126_221707176](https://user-images.githubusercontent.com/37637312/49042833-882a6380-f1c9-11e8-8c08-3e9c02d4d908.png)

**Comment by cibersheep** [comment]
Might this be fixed on dev?
On my m10 and E5 they are translated (dev)

**Comment by Danfro** [comment]
Oh, right. This is fixed in devel now. Thanks for checking.
Then we might as well close this issue I suppose.
