### ISSUE TITLE
[enhancment] different backround image for dash and lock screen

### ISSUE THREAD

**Issue by Danfro** [ubports/system-settings#115]
I would like to have the option to choose a different background image for lock screen and dash.
For the lock screen the background image can be a nice lively photo or something.
For the dash you do need a background that is less busy (?, more even colors), so you can easily see all the app icons.
Therefore I think having the option to set two different images like in Ubuntu would be nice.

**Comment by mateosalta** [comment]
this would be cool, it seems in an earlier version of the system settings had this code.

**Comment by mateosalta** [comment]
![Screenshot_2020-02-04_09-41-04](https://user-images.githubusercontent.com/1965279/73760317-c8249900-4732-11ea-8677-622834b2201e.png)
It needs some work, the welcome screen overlay isn't too bad, but we need to make a simplified overlay that will look like the current dash.

Also  change the selection box, possibly to a check box

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/115
