### ISSUE TITLE
Keyboard layout list is slow to scroll

### ISSUE THREAD

**Issue by lduboeuf** [ubports/system-settings#122]
When accessing keyboard settings from the indicator menu, an exhaustive list of keyboard layouts is shown. If i want to select e.g Vietnameese i have to swipe bottom up 42 times. Any suggestions ?

Accessing keyboard layouts from Settings don't give you the full list, so it is not a pb

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/122
