### ISSUE TITLE
Clicking "Forget this network" doesn't kick the user back to the network list 

### ISSUE THREAD

**Issue by tsimonq2** [ubports/system-settings#125]
When wanting to forget a network in the Wi-Fi settings, tapping "Forget this network" should either kick the user back to the list of networks they can connect to, or switch to a string like "Connect to this network" and hide "IP address". As it is right now, the user doesn't know anything happened.

16.04 devel hammerhead

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/125
