### ISSUE TITLE
Images in "Background" take a notable time to render

### ISSUE THREAD

**Issue by tsimonq2** [ubports/system-settings#127]
The images that the user is able to select in "Background" load pretty slowly, which can be offputting to a new user.

Perhaps this should be rendered in the background when systems settings is started? It rerenders every time the menu is opened. 

16.04 devel hammerhead

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/127
