### ISSUE TITLE
"Brightness & Display" Adjust automatically checkbox is a bit sticky

### ISSUE THREAD

**Issue by tsimonq2** [ubports/system-settings#128]
I'm able to tap the "Adjust automatically" checkbox maybe once, but after that it refuses to toggle or do anything. If I swipe down and adjust it from the notifications menu (for lack of a better term) it works, and it reflects it in the settings menu, but I still can't toggle it.

16.04 devel hammerhead

**Comment by cibersheep** [comment]
- Can't reproduce this issue on OTA9 E5HD.
- We might want to change the Checkbox for a Switch

**Comment by mateosalta** [comment]
agreed, should be the same as the drop down
