### ISSUE TITLE
Add a "test keyboard" menu in "Language & Text" settings 

### ISSUE THREAD

**Issue by tsimonq2** [ubports/system-settings#129]
It would be nice to be able to test any keyboard settings changes you just made immediately after making them, without having to find an app to act as a a guinea pig (plus switching back and forth, etc.)

A submenu in "Language & Text" would absolutely do the job.

16.04 devel hammerhead

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/129
