### ISSUE TITLE
Switching channel

### ISSUE THREAD

**Issue by mihaelmilea** [ubports/system-settings#13]
Device: turbo
Channel: devel
Build: 24

The possibility of choosing upgrade channel in turbo device doesn't work. I choose 
Settings -> Updates -> Update settngs (yes, there is an error here, there is an "i" missing) -> Channels and there there is an empty list with the tile "Channel to get updates from".

**Comment by mihaelmilea** [comment]
Now, in build 25, it works. It displays the channels. It is still missing the "i" but that is just cosmetics :). I think this can be closed now, thank you.

**Comment by mariogrip** [comment]
Fixed now, Thank you for reporting :)
