### ISSUE TITLE
Keyboard themes aren't descriptive enough 

### ISSUE THREAD

**Issue by tsimonq2** [ubports/system-settings#130]
There should either be a preview for the keyboard theme or some sort of color description or something describing each keyboard layout under "Language & Text". New users probably won't know what a "Suru" is, and either way, would probably want to see what they're getting for a theme.

16.04 devel hammerhead

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/130
