### ISSUE TITLE
Auth SHA256 unavailable for VPN

### ISSUE THREAD

**Issue by steackfrite** [ubports/system-settings#133]
Hello Team,

I am trying to connect a fairphone to an openvpn server through the system vpn but as I have enable "auth SHA256" on the openvpn server I am not able to connect to it as I can't add the option "auth SHA256" in the "manual configuration".

Is there a workaround?

Server conf:
`local *.*.*.*`
`port 1194`
`proto udp`
`dev tun`
`ca x.crt`
`cert x.crt`
`key x.key `
`dh x.pem`
`server 10.8.0.0 255.255.255.0`
`ifconfig-pool-persist ipp.txt`
`push "redirect-gateway def1 bypass-dhcp"`
`push "dhcp-option DNS 194.134.4.1"`
`push "dhcp-option DNS 194.134.0.49"`
`keepalive 10 120`
`tls-auth x.key 0`
`cipher AES-256-CBC`
`user nobody`
`group nobody`
`persist-key`
`persist-tun`
`status openvpn-status.log`
`log-append  /var/log/openvpn.log`
`verb 5`
`explicit-exit-notify 1`
`key-direction 0`
`auth SHA256`

client conf:
`client`
`dev tun`
`proto udp`
`remote x.x.x.x 1194`
`resolv-retry infinite`
`nobind`
`persist-key`
`persist-tun`
`ca x.crt`
`cert x.crt`
`key x.key`
`remote-cert-tls server`
`tls-auth x.key 1`
`cipher AES-256-CBC`
`verb 3`
`auth SHA256`
`key-direction 1`

Infos:
Phone: Fairphone 2
OS: Ubuntu 16.0.4 (OTA-7)
openvpn server:  OpenVPN 2.4.6
OS : Fedora release 27
openvpn client: 2.4.6
OS : win 10 pro

Thanks for your help!

Regards,

Steackfrite

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/133
