### ISSUE TITLE
Radio settings (APN) need options for MCC and MNC

### ISSUE THREAD

**Issue by Flohack74** [ubports/system-settings#134]
Certain providers will require slight tuning of MCC and MNC:

* https://en.wikipedia.org/wiki/Mobile_Country_Code
* https://en.wikipedia.org/wiki/Mobile_Network_Code

If one cannot enter or change those numbers then connectivity and roaming might be impaired.

**Comment by Thieb67k** [comment]
Thanks for that post.
According to my provider, I have to add a MCC and MNC numbers somewhere in the settings (add an access point) but I cannot add those data. Where shall I do it?

**Comment by Flohack74** [comment]
@Thieb67k that is the problem right now, you cannot set them :) - we need to implement this first...
I dont know if Ofono would handle this if you add it to some config file. That could be an option before th GUI is finished

**Comment by busyrock** [comment]
After I change the MCC and MNC of sim card APN to other value in the phone, the changed APN option disappears. Does the fixed IMSI cause this problem? I find using the unmatched MNC can realize SMS sending with openbts, but it can not recognize GPRS.

**Comment by Flohack74** [comment]
@busyrock no idea what you are talking about. Are you sure you are talking about Ubuntu Touch OS?

**Comment by busyrock** [comment]
emmmm……I just find this issue communication through searching MNC. I feel sorry about that if it should not talk about other question beside ubuntu touch os here T^T

**Comment by Flohack74** [comment]
Please do not comment on issues where you dont know what they are about ^^ it will not help you in the end much.

**Comment by Flaburgan** [comment]
I confirm that with the french network SFR I need to set MCC and MNC to receive MMS. Please add those settings to UT :smile:

**Comment by Flohack74** [comment]
We have an idea to use this database in the UI: https://wiki.gnome.org/Projects/NetworkManager/MobileBroadband/ServiceProviders - that should help getting the right values.

**Comment by Flohack74** [comment]
Oh no! That database doe snot contain MCC and MNC values it seems. Or I am too stupid to see :) - we will investigate further. But basically there should be a DB we can use

**Comment by Flaburgan** [comment]
How to get the right data is one thing, but isn't this issue about giving the power to the user to fill the data?

I'm a tech savvy user, is there a way for me to fill those data even without a GUI? Or are those field not stored at all at the moment in UT?

**Comment by Flohack74** [comment]
I think thats not stored at all ATM. Also, I have to understand why this entry is necessary, it should be saved on the SIM card and be an informative data only.

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/134
