### ISSUE TITLE
Wifi: enable static IP address configuration

### ISSUE THREAD

**Issue by menschel-d** [ubports/system-settings#139]
Device: frieza
Channel: 16.04/stable
Version: OTA-8

Currently, connecting to a Wifi-network implicitly assumes the usage of DHCP.
It is not possible to manually configure the wireless network interface through `system-settings`.
This restriction is old [1] and well known:

> "In future this screen might also allow entering a static IP address,
>  bug 1445772, and contain router and DNS information." [2]

Fortunately, ubports comes preinstalled with `nmtui`,
which can be used to configure a static IP address from the command line.

[1] https://bugs.launchpad.net/ubuntu/+source/indicator-network/+bug/1445772
[2] https://wiki.ubuntu.com/Networking#A.2BIBw-Wi-Fi.2BIB0_settings_.28phone.29

**Comment by Fuseteam** [comment]
i have found another workaround:
- sudoedit /etc/NetworkManager/system-connections/SSID
- under `[ipv4]` change `auto` to `manual`
- add `address=<STATICIP/SUBNET,GATEWAY>`
- add `dns=<DNSIP>`
- save and run `sudo service network-manager restart`

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/139
