### ISSUE TITLE
System Settings is unresponsive while update is being downloaded

### ISSUE THREAD

**Issue by myii** [ubports/system-settings#143]
Discussed this in the [Telegram SuperGroup](https://t.me/ubports) and also confirmed by @jonnius:

> myii, [18.04.19 21:56]
> ![image](https://user-images.githubusercontent.com/10231489/56413465-813ae500-627f-11e9-9dde-55772d45e458.png)
> 
> myii, [18.04.19 21:56]
> Tried to download a system update on `devel`.  It got stuck while downloading.
> 
> myii, [18.04.19 21:57]
> Every time I open Systems Settings, it's now frozen with the part shown in the image above.
> 
> myii, [18.04.19 21:58]
> OK, it's just started working after a number of minutes.
> 
> myii, [18.04.19 21:58]
> Seems to get stuck while downloading the update.
> 
> Jonatan Hatakeyama Zeidler, [19.04.19 05:56]
> [In reply to myii]
> Happens for me all the time

**Comment by nnn19** [comment]
This still persists.

And while inside "Update Settings", the system is too slow (to an unacceptable level) that we might have pressed the back button or other few times.

LG Nexus 4 running UT 16.04 (OTA-10).

Natarajan N Napoleon
@NatarajanNNapoleon

**Comment by Fuseteam** [comment]
from marius's lomiri overview video i seem to remember its due to it not displaying the correct state of the update iirc

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/143
