### ISSUE TITLE
Un-intuitive password change process for 4-digit passcode

### ISSUE THREAD

**Issue by wayneoutthere** [ubports/system-settings#144]
If you go to system settings / security & privacy / locking and unlocking /  lock security you have 3 options: swipe (no security), 4-digit passcode and passphrase.

For the 4-digit passcode, once you have set it, does not have a 'change passcode' option. The way I have to change it is to change to 'swipe (no security)' and then go back into 4-digit passcode to create an updated passcode.

What I expect is exactly what is in the 'passphrase' option where you can enter:

* existing passcode
* choose new passcode
* confirm passcode

Thanks!

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/144
