### ISSUE TITLE
tap twice on storage results in missing back button on storage page

### ISSUE THREAD

**Issue by Danfro** [ubports/system-settings#157]
E5, RC 2019-W20

Steps to reproduce:
- open system settings
- open info
- tap storage once
- tap storage a second time before the page is opened

expected result:
- storage page is loaded, back button available

actual result:
- storage page is loaded
- page does load storage values (circles appear for a few seconds)
- after storage values are loaded the back button disappears

reproducible: 
- always when tapping twice
- never when tapping only once

**Comment by cibersheep** [comment]
Confirmed on E5HD RC 2019-W25

**Comment by kugiigi** [comment]
I see this issue in many pages from time to time and it seems to happen on heavy pages. Probably an issue with UITK?

**Comment by cibersheep** [comment]
Could it be AdaptivePageLayout?

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/157
