### ISSUE TITLE
[E5HD] Changing Hotspot Password with Hotspot on Makes Device Reboot

### ISSUE THREAD

**Issue by cibersheep** [ubports/system-settings#163]
**Steps to Reproduce:**
- Turn on hotspot (make sure is on: icon is on the indicator)
- Open hotspot configuration
- Change password and tap on save

**Expected behaviour:**
- Configuration is saved

**Current behaviour:**
- Spinner is on save until stops spinning
- Device reboots

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/163
