### ISSUE TITLE
[E5HD] Hotspot Doesn't Turn on

### ISSUE THREAD

**Issue by cibersheep** [ubports/system-settings#164]
Steps to Reproduce:
- Pull down indicator / Go to System Setting > Hotspot and turn on Hostpot

Expected Behaviour:
- Hotspot to turn on

Current Behaviour:
- Wifi turns off and on again. Hotspot switch shows green
- Switching off and on seems to turn on Hotspot  (icon is shown on indicator) but it doesn't connect (see https://github.com/ubports/ubuntu-touch/issues/806)

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/164
