### ISSUE TITLE
Cursor Focus Lost when Changing Hotspot Password

### ISSUE THREAD

**Issue by cibersheep** [ubports/system-settings#165]
**Steps to Reproduce:**
- Go to System Settings > Hotspot and tap on Change password
- Try to tap on Show password

**Expected:**
- Checkbox to be marked

**Actual behaviour:**
- It's not possible to tap on checkbox

**Workaround:**
Tap first on text field

In the screenshot you can see the cursor somwhere between checkbox and button

![imatge](https://user-images.githubusercontent.com/6640041/59984099-c6381a80-9626-11e9-9985-be002487a3ce.png)

![imatge](https://user-images.githubusercontent.com/6640041/59984030-09de5480-9626-11e9-9f10-afca3e3087e9.png)

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/165
