### ISSUE TITLE
Dark Style Preference

### ISSUE THREAD

**Issue by bhdouglass** [ubports/system-settings#166]
Add a new toggle button for "Prefer dark style". This will allow the user to indicate that they wish to have a dark theme for the system and apps. But this will not force the apps to change their themes, but rather they will opt into this setting.

When implementing this we should respect the standard proposed by elementary ( https://medium.com/elementaryos/the-need-for-a-freedesktop-dark-style-preference-614f501ae4ca ).

To facilitate this new toggle, we might consider creating a new "Appearance" section of the system settings (and include the keyboard theme there as well?).

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/166
