### ISSUE TITLE
Previous Network: Password not Visible on Suru Dark

### ISSUE THREAD

**Issue by cibersheep** [ubports/system-settings#169]
As stated by Mateo:
- System settings -> wifi -> previous networks -> select a previous network -> Show password

Both dots and password is shown on dark text

**Comment by Flaburgan** [comment]
![pwd-unreadable](https://user-images.githubusercontent.com/930064/70948289-682b4380-205b-11ea-8b3d-2e7cb0cd1737.jpg)

I'm also facing that issue.

**Comment by UniversalSuperBox** [comment]
This was fixed by https://github.com/ubports/system-settings/pull/180, which is merged and in devel.

**Comment by cibersheep** [comment]
Sorry I forgot to close it
