### ISSUE TITLE
[Notifications] Grouped Notifications Misses Notification Types

### ISSUE THREAD

**Issue by cibersheep** [ubports/system-settings#174]
Under Notifications we have 4 types of notifications per app:
- Sound
- Vibration
- Bubbles
- Notification Center

Under grouped apps by notification type we only have:
- Apps that notifies with sound
- Apps that notifies with vibration

we miss the other two types

2 Groups of notification types:

![imatge](https://user-images.githubusercontent.com/6640041/61784963-05ff4700-ae0b-11e9-90fe-6c9b35417271.png)

4 types of notifications for each app

![imatge](https://user-images.githubusercontent.com/6640041/61785058-33e48b80-ae0b-11e9-8dbc-b26c4b48b3cb.png)

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/174
