### ISSUE TITLE
OTA-10. "Updates" Screen showing Ubuntu Touch Version 8  while Downloading / Updating

### ISSUE THREAD

**Issue by nnn19** [ubports/system-settings#175]
OTA-10. While updating...the existing Ubuntu Touch Version is shown as 7 under "Recent Updates" and the Downloading / Installing version is shown as 8. 

And after rebooting and finishing the installation, the "Updates" screen - "Recent Updates" shows Ubuntu Touch Version 7  ...  Updated 22 August.

LG Nexus 4 running UT 16.04 (OTA-10).

Natarajan N Napoleon
@NatarajanNNapoleon

**Comment by Fuseteam** [comment]
the version number in the updates section doesn't say much. the real version is seen under about. as long as that shows the correct versioning it should be fine afaik

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/175
