### ISSUE TITLE
Bluetooth Switch not Responding After Connecting to Another Device

### ISSUE THREAD

**Issue by cibersheep** [ubports/system-settings#179]
Tested devices N5 Eedge and E5 RC
1- Turn on bluetooth
2- Pair phone to phone
3- Connect (pin confirmation)
4- Turn off bluetooth from one device

Expected: connection gets off, bluetooh goes off
Actual: Bluetooth switch is off, bluetooth looks on (indicator is on), devices got disconnected, not possible to swith on flight mode on. Reboot is needed.

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/179
