### ISSUE TITLE
Can't login to google account anymore

### ISSUE THREAD

**Issue by j2g2rp** [ubports/system-settings#190]
Since some months ago there isn't possible to synchronize to google account anymore, looks, like google revoked our authentication.
Expected behavior:
login to google account to synchronize calendar or contacts.
I don't know if it just mater of a security configuration...

**Comment by UniversalSuperBox** [comment]
Hi @j2g2rp, thanks for reporting this issue. It appears to be a duplicate of https://github.com/ubports/ubuntu-touch/issues/1202, so I'll close this report in favor of that one.
