### ISSUE TITLE
network setting on dual sim devices does show only one number

### ISSUE THREAD

**Issue by Danfro** [ubports/system-settings#197]
Go to system settings/network using a dual sim device e.g. E5.

For the first sim card the IMEI number is displayed. For the second sim the phone number is displayed.

Likely related to [address-book-app #106](https://github.com/ubports/address-book-app/issues/106).

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/197
