### ISSUE TITLE
Upon relaunch About/Storage "by name" listed when still sorting apps "by size" (if previously selected)

### ISSUE THREAD

**Issue by BatteryJuice4** [ubports/system-settings#201]
What happened:
Going to the Storage page under About and changing the installed apps sorting method from "by name" to "by size" works. However, when closing the app and relaunching, the apps are still sorted by size, but the drop-down menu has returned to "by name."

What I expected to happen:
Upon reopening the System Settings app, for the apps to be sorted by what is shown in the drop-down menu. Either the apps to return to sorting by name, just as the menu listing does, or the menu to still show "by size," as the apps are still sorted by size.

Steps to reproduce:
Open System Settings app, go to About and then Storage. Touch "by name" to reveal a list of sorting options. Select "by size" (everything looks right for now). Go back to About and close the System Settings app (by swiping it away). Open System Settings again and go back to Storage. Apps are still sorted "by size" but the drop-down menu reverted back to "by name."

Software Version: Ubuntu 16.04 (2020-01-19) devel, version 1339, on Nexus 5 (hammerhead)

Screenshots:

Default "by name"
![screenshot20200118_142255364_resized_1](https://user-images.githubusercontent.com/60047383/72675039-6ed71d00-3a44-11ea-92ed-e7fa2d7f4b62.png)

"by size" selected. Everything looks good.
![screenshot20200118_142239162_resize_2](https://user-images.githubusercontent.com/60047383/72675089-ef961900-3a44-11ea-90b6-d171097caf31.png)

Close and reopen System Settings app. Says "by name" but sorts by size
![screenshot20200118_142236511_resized_3](https://user-images.githubusercontent.com/60047383/72675127-63d0bc80-3a45-11ea-8732-784f18256fb2.png)

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/201
