### ISSUE TITLE
Brightness slider is movable when auto adjust is on

### ISSUE THREAD

**Issue by mateosalta** [ubports/system-settings#204]
Turn on auto brightness in system settings, then interact with the brightness slider.

What happens:
- slider moves freely with no effect

What should happen:
- slider should be locked in place or disabled in some way interactively and visually, but not in a way that stops it from reporting the current brightness that auto brightness has set it.

**Comment by FlavioMala** [comment]
It is still movable here:
![screenshot20201128_101931328](https://user-images.githubusercontent.com/50835740/100498589-936f4b80-3163-11eb-81b0-e54d07a6ee21.png)

BQ E5, after “update 634" (dev ch) -- today.

**Comment by FlavioMala** [comment]
(“il postino suona sempre due volte" , ma anche 3 o 4)
System settings with "auto on":
![screenshot20201128_102948462](https://user-images.githubusercontent.com/50835740/100498863-72a7f580-3165-11eb-85aa-f1176b95dd63.png)
Set "auto off" THEN MOVE the slider QUITE A BIT (brightness should change):
![screenshot20201128_102957377](https://user-images.githubusercontent.com/50835740/100498911-df22f480-3165-11eb-9a18-ed0c82c86876.png)
Now set "on" again. The brightness changes but the slider does not indicate the correct status:
![screenshot20201128_103006632](https://user-images.githubusercontent.com/50835740/100498966-388b2380-3166-11eb-9fac-e17d2614cf84.png)
Toggle it on/off 2 or 3 (or more) time and slider return to correctly  report brightness.
(That is, it moves between the two on / off levels if you continue "toggling")

**Comment by jonnius** [comment]
I confirm this is fixed on RC Xperia X.

**Comment by jezek** [comment]
Device: FP2
OS: 2020-W49

In brightness settings:
- when auto enebled: slider can not be moved
- when auto disabled: slider can be moved and brightness is adjusted.

**Comment by josevidalrt** [comment]
Device: BQ E4.5
    Channel: rc
    Build: 2020-w49

Description:
The brightness slider on the **indicator screen** can be moved when auto adjustment is on. Under System Settings -> Brightness the brightness slider cannot be moved when auto adjustment is set.

Expected behavior:
The brightness slider on the indicator screen also cannot be moved when auto adjustment is on.

Thanks

**Comment by mateosalta** [comment]
yes, this is the bug for the system settings app - please file a separate bug for the indicator

**Comment by mateosalta** [comment]
hi @josevidalrt and @FlavioMala I have moved your bug reports to the indicator-power.
