### ISSUE TITLE
Feature: setting to disable auto join previous network 

### ISSUE THREAD

**Issue by mateosalta** [ubports/system-settings#205]
![Screenshot_2020-01-21_08-29-14](https://user-images.githubusercontent.com/1965279/72813223-9c7cbb80-3c28-11ea-8c56-ee73187691f1.png)

Implement checkbox that allows users to not auto connect to previous networks.
- users feel more in control
- perhaps a small effect against mitm attack - if in public and user has already connected to a same named network before 

Seems like a useful not yet made thing that was in the design docs for the system settings

**Comment by mateosalta** [comment]
gsettings exist: com.canonical.indicator.network auto-join-previous true

should be simple to hook up :)

**Comment by mateosalta** [comment]
in testing is doesn't seem to do anything though

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/205
