### ISSUE TITLE
When choosing CA certificate strange content hub display

### ISSUE THREAD

**Issue by mateosalta** [ubports/system-settings#206]
Select a Wifi security that lets you choose a ca certificate

What happens: 
Content hub is shown without a Header, cuts off the app icons, doesn't allow selecting(on rotation) and other graphical bugs.

Should happen: 
content hub shows proper, and allows selection of certificate

![photo_2020-01-22_08-19-38](https://user-images.githubusercontent.com/1965279/72901777-f8f6de00-3cef-11ea-9338-ba07172fde4d.jpg)
![photo_2020-01-22_08-19-08](https://user-images.githubusercontent.com/1965279/72901778-f8f6de00-3cef-11ea-9ce9-a1246cbe4ba3.jpg)

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/206
