### ISSUE TITLE
preview header for background should be transparent

### ISSUE THREAD

**Issue by mateosalta** [ubports/system-settings#207]
https://github.com/ubports/system-settings/blob/2a041c6fbc6d07dd4b82bb10cd5d0b7c604666ad/plugins/background/Preview.qml#L120-L129

new uitk sets header background color hiding previous work to make a transparent for the ease of previewing the background.

Also move giant buttons to header for better image preview experience, and more consistent page navigation

![photo_2020-01-22_09-25-05](https://user-images.githubusercontent.com/1965279/72907278-37dd6180-3cf9-11ea-91e2-cdc48b9c7345.jpg)

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/207
