### ISSUE TITLE
Suggestion: Rename 'Update settings' to 'Update Ubuntu Touch OS Settings' in 'Updates' section

### ISSUE THREAD

**Issue by wayneoutthere** [ubports/system-settings#227]
I have always struggled with quickly finding the operating system and channel settings in Ubuntu Touch.  The rest is really good on this 'update' screen except this one thing.  It should be more clear in the the name where to find this, I feel.  Thanks.

**Comment by cyberpunkedu** [comment]
Indeed the words "Update settings" could be a bit clarified.
"System Update Settings" would be a shorter alternative.
Then you would also want to change "Updates" to "System Updates" ; however, some apps also update in that area. 

Interesting issue.

**Comment by wayneoutthere** [comment]
Hmm.  you made me think again. 

Perhaps this:

"Updates" to 'Software Updates"

The top section of this page remains as it is now, but 'Software is Up to Date" message becomes 'Application Software is Up to date"

Then, at the bottom:

"Update Settings" --> "System Update Settings"

So we are splitting this 'Software Updates" page into two sections:

1. Application Software and 
2. System Software (Operating System)

**Comment by dobey** [comment]
> however, some apps also update in that area.

Though, app update could be removed so we rely totally on open store for those. This, I think, is also part of the cause for confusion. FWIW, this was slated to be removed anyway before Canonical dropped the project.

**Comment by wayneoutthere** [comment]
that.... is a seriously good point and a worthy point.  why in the world are the apps even there when they are taken care of perfectly in OpenStore?  nice thinking!

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/227
