### ISSUE TITLE
Suggestion: Add detailed description section to each OS channel

### ISSUE THREAD

**Issue by wayneoutthere** [ubports/system-settings#228]
I have always struggled knowing the clear difference between the various Ubuntu Touch channels.  Currently there are four channels and I would propose adding a description field to each channel to look something like this, and also in order of *higher danger lower down the list* as follows:

Channel name: Stable
Channel nickname: n/a
Channel Description: The safest, longest support channel with the highest level of stability.  Best choice if you aren't sure what channel to choose and also the default channel of all Ubuntu Touch installations

Channel name: Release Candidate
Channel nickname: "RC"
Channel Description: Allows you to try OS changes that come out with Over-the-Air(OTA) updates before they are released to the Stable channel.  Introduces some degree of instability to the OS.

Channel name: Development
Channel nickname: 'Devel"
Channel description: Gives you any changes applied by developers to the OS.  Also introduces a fairly high level of instability to the experience producing increased number of reboots and crashes.  Recommended for developers or adventurers.

Channel name: Edge (by the way this has lower case in name and maybe we should make consistent?)
Channel nickname "bleeding edge"
Channel description: Designed for 'living on the edge'.  Introduces the very latest and craziest updates guaranteed to introduce instability and crashes into you day.  Recommended only for experienced developers focused on the deep details of Ubuntu Touch OS

I was also thinking about breaking it out into 'recommended for:' as it's own field like this:

Channel name:
Channel nickname: 
Channel description: 
Recommended for:

I think some or all of these changes would make things much more clear once users land in this area of the settings.

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/228
