### ISSUE TITLE
Messy System Settings Icons

### ISSUE THREAD

**Issue by cibersheep** [ubports/system-settings#246]
System Settings looks messy:

- Icons dor Network, Personal etc. are too big
- They don't sort alfabetically

I'm still thinking that ListView is more tidy. 

![imatge](https://user-images.githubusercontent.com/6640041/88533278-4ee17100-d006-11ea-969d-386bbbd69eb1.png)

**Comment by mateosalta** [comment]
I'm wondering if the grey is making them look slightly blury

**Comment by cibersheep** [comment]
I may just close this issue as I'm the only one thinking this :D
