### ISSUE TITLE
Background image folder?

### ISSUE THREAD

**Issue by seteahconnoc** [ubports/system-settings#251]
Hi,

In which folder do I find my custom background images? I've changed the background images a few times using: `System Settings -> Background -> Custom` Now, I want to collect all my background images and save them elsewhere.

I already posted this issue here: https://forums.ubports.com/topic/4753/wallpaper-folder?_=1597839950625 By now, there are no responses.

Any help would be welcome.

---

bq Aquaris E5 HD, Ubuntu 16.04 (OTA-12)

**Comment by mateosalta** [comment]
/var/lib/lightdm-data/phablet/ubuntu-system-settings/Pictures

**Comment by seteahconnoc** [comment]
@mateosalta Thank you.

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/251
