### ISSUE TITLE
divider on some locales overprints icons on new (old) design

### ISSUE THREAD

**Issue by Danfro** [ubports/system-settings#253]
This issue is a follow up on the revival of the new/old icon design [#324](https://github.com/ubports/ubuntu-touch/issues/324).

To reproduce do the following steps:
`indicator -> System -> About This Device... -> back icon`

Only when accessing system settings page via those steps, the security&privacy icon is overlapped by the separator in some locales. This could be reproduces with several locales (Czech, Norwegian, German, Slovak). The issue does not occur with English locale.

![screenshot taken from other issue](https://user-images.githubusercontent.com/37637312/92033921-c4aacc00-ed6c-11ea-8400-53c9e06f6009.png)

**Comment by Danfro** [comment]
Discovered today that
1. this seems to apply to all "back access" ways. `Indicators -> Network settings ->back` yields the same separator issue
2. all separators are affected, notifications is overprinted too e.g. in German layout

![screenshot20200903_105931712](https://user-images.githubusercontent.com/37637312/92247204-2da65700-eec7-11ea-89b6-957d0f2c78ef.png)

**Comment by mateosalta** [comment]
also try the search function, the dividers go crazy there :)

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/253
