### ISSUE TITLE
VPN preview dialog buttons do not meet the HIG standards

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/system-settings#254]
The VPN page in system-settings has a rather strange behavior quirk. When you tap on a VPN connection, you might expect to go directly to the connection's configuration. Instead, a "Preview" dialog pops up telling you about the connection and offering options to change it.

This would probably be fine, but the dialogs generally aren't very helpful. For example, consider the "No certificate" dialog:

![Screenshot of a dialog, with the heading "VPN". Text: This VPN is not safe to use. It does not provide a certificate. The VPN provider could be impersonated. Options are Remove or Change](https://user-images.githubusercontent.com/21966173/93912971-11c5f200-fcca-11ea-9d3f-daa70995ba32.png)

There is no way to leave this dialog without making changes to the connection. The "Remove" action, which to me is destructive rather than neutral, is colored neutrally.

This issue isn't regarding the general UX of this preview page (that's another discussion), but there are three small changes that could be done together to make the experience better.

1. Add or enable the "Cancel" option, allowing the user to make no changes from this dialog whenever it appears
1. Recolor the available options to meet our HIG
1. Make the dialog's options meet the system standard. They should be laid out in rows, not columns.

The dialog is created in [VpnPreviewDialog.qml in settings-components](https://github.com/ubports/settings-components/blob/406898e9603c415ee8abbc743af57e2c4bbdc9ff/plugins/Ubuntu/Settings/Vpn/VpnPreviewDialog.qml).

**Comment by mateosalta** [comment]
oh, that is strange. I think we should move that warning to when you want to enable the vpn. but not have the remove action.
So:
- Add vpn, let user setup as needed
- when enabling non secure setup - warn, but let user select enable or cancel
- remove dialog from editing the vpn

**Comment by UniversalSuperBox** [comment]
I agree. Anything is probably better than what's there now, though...

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/254
