### ISSUE TITLE
Impossible to remove a custom image in Background menu

### ISSUE THREAD

**Issue by ghost** [ubports/system-settings#274]
How to reproduce:
Open the System Settings app.
In Personal, select Background.
In Custom, select Remove images...
Select a previously imported image (the upper right corner becomes orange).
The button in the lower right is still grey and labelled No images selected.
If you select the lower left button labelled Cancel, it open the Content Hub to choose an application (same functionality as Add an image...).

Expected behavior:
The lower right button should be dark grey and labelled something like Confirm removal.
The lower left button should still be labelled Cancel but should allow to cancel the action of removing a custom image.

Configuration:
FP2 OTA 15 stable

**Comment by mateosalta** [comment]
work towards fixing this in: https://github.com/ubports/system-settings/pull/208

workaround: add a new image, after adding one new image, the removal button will now work

**Comment by mateosalta** [comment]
https://github.com/ubports/ubuntu-touch/issues/803

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/274
