### ISSUE TITLE
Change about icon to "info" icon?

### ISSUE THREAD

**Issue by mateosalta** [ubports/system-settings#277]
https://github.com/ubports/system-settings/blob/bf1c2d30b00cb04bf7506f34dbe8dffc7e8f6cf3/plugins/about/about.settings#L2

The about page shows the ubuntu symbolic icon - I was thinking the "info" icon may be a better fit for this settings entry.

**Comment by UniversalSuperBox** [comment]
Sounds good to me, especially as we ship this app on more operating systems than Ubuntu Touch now.

**Comment by mariogrip** [comment]
Yeah i fully agree with this

**Comment by mateosalta** [comment]
Cool, I will make a pull then :)

**Comment by mateosalta** [comment]
https://github.com/ubports/system-settings/pull/280

**Comment by cibersheep** [comment]
Shows info icon on E5

**Comment by lgtrombetta** [comment]
Shows on the Nexus 6P

**Comment by dadandalive** [comment]
Testing on Nexus 5 - RC 2021-W10. Not sure how the info icon looks like. This is the icon I see: 
![logo](https://user-images.githubusercontent.com/37327758/110918303-4cc0ee00-831b-11eb-9dcb-ac471bc57e93.png)

**Comment by mateosalta** [comment]
> Testing on Nexus 5 - RC 2021-W10. Not sure how the info icon looks like. This is the icon I see:
> ![logo](https://user-images.githubusercontent.com/37327758/110918303-4cc0ee00-831b-11eb-9dcb-ac471bc57e93.png)

that one stays the same, the icon that gets you to the page used to be the ubuntu icon, it is now a "i" in a circle, bottom of the screen before reset:

![screenshot20210312_082221567](https://user-images.githubusercontent.com/1965279/110952848-48d99f80-830c-11eb-8dae-d7c5bbcc24c4.png)
