### ISSUE TITLE
Keyboard theme page doesn't correctly select the currently active theme

### ISSUE THREAD

**Issue by kugiigi** [ubports/system-settings#281]
### Steps to Reproduce
1. Opens settings app
2. Go to `Language & Text > Keyboard theme`
3. Select a theme other than `Ambiance`
4. Go back to previous page then go back the `Keyboard theme` page

### Expected Result
The currently active theme is selected in the list

### Actual Result
The first item, Ambiance, is always selected regardless of the active theme.

**Comment by CDLProduction** [comment]
Tested on redmi note 7 lavender on current rc version 2021-w08.
The active theme is checked in the list. 
Behavior as expected.

**Comment by cibersheep** [comment]
Looks fixed on E5

**Comment by dadandalive** [comment]
I confirm, the Keyboard theme selection does not get altered on Nexus 5 (RC W2021-10), and the chosen theme is the one actually used by the keyboard (despite general theme selection through Theme switcher app).
