### ISSUE TITLE
URI Handling is different when app is close and when already open

### ISSUE THREAD

**Issue by kugiigi** [ubports/system-settings#284]
### Steps to Reproduce
1. Make sure system settings app is not open.
2. Open Morph
2. Go to the address `settings:///online-accounts`
3. Go back to morph and try the same URL again.

### Expected Results
System settings app opens (if close) or goes into focus (if already open) and go directly into the online accounts page.

### Actual Results
When settings app is not open, it opens and go directly into the online accounts page.
When settings app is already open, it goes to focus and stays in the main page.

### Additional Information
Using the URL `settings:///system/online-accounts` works in both scenarios. Apparently, the URI handler when theh app is already open specifically checks the string `settings:///system`.

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/284
