### ISSUE TITLE
Add 3G/4G as connection 

### ISSUE THREAD

**Issue by Mannshoch** [ubports/system-settings#29]
At moment there are no connection types without 2G. Please add a 3G/4G connection.

**Comment by Mannshoch** [comment]
Is this Request at the correct position?

**Comment by NeoTheThird** [comment]
Actually it should be at github.com/ubports/ubuntu-touch, but i'm wondering why you would want that? The phone will always use the fastest connection that it is available at a sufficient signal strength. I don't even think ignoring the 2G signal would result in less power consumption, so what do you want to achieve here?

**Comment by Mannshoch** [comment]
It's at moment, as far I know, the Easiest way to prevent a Phone to connect to IMSI Catcher. I tested these in a routed Lineage OS, It work there without Problems.

**Comment by NeoTheThird** [comment]
Good point. I'll move the issue.

**Comment by NeoTheThird** [comment]
This issue was moved to ubports/ubuntu-touch#406
