### ISSUE TITLE
System Settings can't fetch app-updates from certain apps in OpenStore

### ISSUE THREAD

**Issue by ivoxavier** [ubports/system-settings#32]
Hi 

As the title said system-settings can't fetch some app-updates from certain apps from OpenStore.

How to reproduce? Just wipe your phone, then open each app (OpenStore and SystemSettings). Check my file attached. 

Device:FP2
Channel:Devel
Version:270

![sem titulo](https://user-images.githubusercontent.com/16002474/34365385-83e3a2b8-ea87-11e7-84f5-54cca19a37e6.png)

**Comment by UniversalSuperBox** [comment]
https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/32
