### ISSUE TITLE
Auto cache cleaning

### ISSUE THREAD

**Issue by BlueKenny** [ubports/system-settings#62]
i think it is important to have an option to clean the cache or an automatic way to do this.

After a couple of days i need to clean the cache manualy to be able to update the system.

A idea could be, after removing "update" from the last updated list in setting, this update can be removed from the partition, so the user doesn't need to take this task....

or on a reload of new updates, it look for the one that are 2-3 update ago and delete it(no looking on the time as Stable needs more time than Devel ).

this is only my opinion, the "normal" user don't clean cache manualy

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/62
