### ISSUE TITLE
forget wifi connection option needs 'back' navigation to overview page

### ISSUE THREAD

**Issue by matv1** [ubports/system-settings#68]
in: Wi-Fi --> Previous Networks --> [Selected network]
When using the ' Forget Network' option, The chosen network visibly doenst seem to get removed, when in fact it has been. It seems like that after removing the wifi stored connection, the page should go back to the main wifi-connections overview page (this is what happens in 15.04), but it doesnt do that.

Device: Meizu Pro 5
Channel: 16.04 RC (2018-W27)

**Comment by guyluz11** [comment]
Dose not effect me on OnePlus one RC 26 (20180w48)

**Comment by matv1** [comment]
device: Meizu Pro5
channel: RC 2018-W48
issue solved. No noticeable side effects
