### ISSUE TITLE
[Xenial] Where is printing?

### ISSUE THREAD

**Issue by Daniel20000522** [ubports/system-settings#73]
**Device: Nexus 4
Channel: Dev
Build: 2018-08-10**

After entering "Print", only the category in which the printing is to be displayed is displayed.
Look at this screenshots.

![screenshot20180812_000654255](https://user-images.githubusercontent.com/30577245/43996494-0609ea5a-9dc4-11e8-81a4-26589cb4e3f4.png)
![screenshot20180812_000841077](https://user-images.githubusercontent.com/30577245/43996495-06274c94-9dc4-11e8-894f-12fc310e1f72.png)

**Comment by Flohack74** [comment]
Printing was targeted for an OTA but then we had to drop it again because of size restrictions for the rootfs. Currently it cannot be added otherwise a few devices cannot install any updates anymore. I close this here as an qnaswered question.
