### ISSUE TITLE
[Xenial] Some elements hidden by Header

### ISSUE THREAD

**Issue by cibersheep** [ubports/system-settings#75]
1. Open Notifications > app
2. First item «enable notifications» switch is hidden behind header
3. Flickable is bad anchored? So it doesn't flick making imposible to access the switch

![imatge](https://user-images.githubusercontent.com/6640041/44313000-d973cb80-a400-11e8-8daa-97c7885e0d86.png)

**Comment by cibersheep** [comment]
Same with Wi-Fi properties
System settings > Wi-Fi > tap on the current connection
![imatge](https://user-images.githubusercontent.com/6640041/44312905-b4cb2400-a3ff-11e8-87a9-2a930c358395.png)

**Comment by cibersheep** [comment]
Image from today fixed notifications area <3
- Notifications for each app: ok after this [comming](https://github.com/ubports/system-settings/commit/aa9d2b2c6bd68b7d35d17d44a83897443b2a4bf7)
- Notifications: Apps that notify with sounds > Title not visible
- Info on current Wi-Fi connection: can't acces «Forgive this wi-fi»

**Comment by lionelb123** [comment]
I have checked this on FP2 and on BQ FHD after installing 'OTA6' version of rc. Can confirm that the fix works in the dialog for all of my installed apps. Notification slider is clear to access
