### ISSUE TITLE
[vivid] [xenial] Language aids interfere with TextFields

### ISSUE THREAD

**Issue by cibersheep** [ubports/system-settings#76]
If «word suggestion» or «spell checking» is activated, interferes in TextFields like browser title bar or and other TextField that checks if TextField.text is empty **and** with clear button (x)

Example:
when typing text in browser address bar, browser history and suggestions should appear: 

Image 1) Word suggestion and Spell checking off
![imatge](https://user-images.githubusercontent.com/6640041/44459689-d3513b00-a60a-11e8-8ccf-45e28a7d1f29.png)

Image 2) Word suggestion or Spell checking on
![imatge](https://user-images.githubusercontent.com/6640041/44459741-01cf1600-a60b-11e8-8aa3-76c4513453dd.png)

**Comment by cibersheep** [comment]
Possible workaround: avoid text aids in TextField:
` inputMethodHints: Qt.ImhNoPredictiveText`

**Comment by cibersheep** [comment]
Browser address bar bug is fixed no in other cases though

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/76
