### ISSUE TITLE
Updated Channel Settings does not reflect on "Update" Screen and "Update settings" Screen

### ISSUE THREAD

**Issue by nnn19** [ubports/system-settings#87]
System Settings - Updates screen
Does not show the currently choosen Channel.

Also under
System Settings - Updates - Update settings - Channels.
When another channel is choosen (a tick mark confirms it) followed by back arrow on left top, the Update settings screen does not reflect the changed channel. It only shows the previously choosen channel ! Even if we go into Channels again and come out, it will not.

And if we come out by another back arrow, the Updates screen does not show the current choosen channel. The user might be under the impression that the channel had NOT been changed.

1. It is better to display the current channel on "Updates" Screen.
2. "Update settings" should show the changed channel name.

Thanks

@NatarajanNNapoleon

**Comment by nnn19** [comment]
The changed channel does not show up when we come out. It still shows the previously choosen channel.

If we re-visit Settings - Updates - Update settings, it shows the changed channel.

**Comment by nnn19** [comment]
Even after several updates...this issue is still there.

LG Nexus 4 running UT 16.04 (OTA-10).

Natarajan N Napoleon

**Comment by nnn19** [comment]
Nice to see that the **systems-settings** is being attended too in the recent versions - there are several improvements done to this. But the mentioned issue is still there.

Hope this will get attended too.

Natarajan N Napoleon

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/87
