### ISSUE TITLE
[Xenial] VPN Manual Configuration Is Not Translatable

### ISSUE THREAD

**Issue by cibersheep** [ubports/system-settings#94]
The component that is open here, is not translatable. I can't find the qml
https://github.com/ubports/system-settings/blob/xenial/plugins/vpn/PageComponent.qml#L91

![imatge](https://user-images.githubusercontent.com/6640041/47594979-35694c00-d97e-11e8-82b5-6043d4d4d3d5.png)

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/94
