### ISSUE TITLE
Updates install button doesn't process

### ISSUE THREAD

**Issue by cyberpunkedu** [ubports/system-settings#96]
Device: Hammerhead
Channel: 16.04/devel
Build: 2018-10-29/2

Steps to Reproduce:
1. Open System Settings
2. Go to updates and download update
3. Press "install"
4. Press "Restart & Install"

Expected:
- System reboots and installs

Actual:
- "Update System" dialogue goes away and nothing happens. No Reboot etc.

Comments:
This behaviour happens quite frequently, and often resolves with multiple attempts. On this build I have tried at least 10 times without the system rebooting/installing.

**Comment by cibersheep** [comment]
I had the same on Dev channel.
Version 676

Try to reboot the device and try again. It solved for me

**Comment by cyberpunkedu** [comment]
@cibersheep thanks, that did indeed solve it this time ;)

What could be causing this issue though?

**Comment by cibersheep** [comment]
I don't know what might have caused it. I have updated again with no problems.
It might have been a «one hit wonder»?

**Comment by cyberpunkedu** [comment]
Could be. I noticed that the "install" button doesn't like to work when another process is running (e.g. podbird playing something). Many one hit wonders going round though.

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/96
