### ISSUE TITLE
Updates don't detect/download on non-wifi connection

### ISSUE THREAD

**Issue by cyberpunkedu** [ubports/system-settings#97]
Device: hammerhead
Channel: 16.04/devel
build: 2018-10-29/2

Even though "automatic updates" is set to only on "wifi", the system should still detect that there is a new update and allow you the choice to download or not on a mobile data connection.

Instead, the update does not even show that it's available.

**Comment by Flohack74** [comment]
Whats worse, the spinner runs forever and you feel that something got stuck.

**Comment by UniversalSuperBox** [comment]
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/97
